services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan serve --host=0.0.0.0 --port=1111
    ports:
      - "1111:1111"
    volumes:
      - .:/var/www
      # Map the frontend folder so Laravel can serve it
      - ../frontend:/frontend
    depends_on:
      - db
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=clothes_rental
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: clothes_rental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
